name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: jruby-10.0.0.0
            os: ubuntu-latest
          - ruby: jruby-9.4.12.0
            os: macos-latest
          - ruby: 3.4
            os: ubuntu-latest
          - ruby: truffleruby-24.2.0
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake test
